import { spawn } from 'node:child_process';
import { config } from './config.js';
import type { ResolvedVideo } from './youtube.js';

export class SunoError extends Error {}

const SUNO_RE = /(^|[./])(suno\.com|suno\.ai)\/(?:s\/[A-Za-z0-9_-]+|song\/|embed\/|clip\/|playlist\/)/;
const SUNO_CDN_RE = /(^|[./])cdn1\.suno\.ai\//;
const UUID_RE = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
const BARE_UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

/** Only treat input as Suno when it's a Suno link, its CDN, or a bare UUID —
 *  a UUID appearing anywhere in an unrelated URL must not hijack other sources. */
export function isSunoUrl(input: string): boolean {
  const t = input.trim();
  return SUNO_RE.test(t) || SUNO_CDN_RE.test(t) || BARE_UUID_RE.test(t);
}

function extractUuid(input: string, html: string): string | null {
  const canonical = html.match(/<link rel="canonical" href="https:\/\/suno\.com\/song\/([0-9a-f-]{36})"/);
  if (canonical) return canonical[1];
  const cdn = html.match(/cdn1\.suno\.ai\/([0-9a-f-]{36})\.mp3/);
  if (cdn) return cdn[1];
  const direct = input.match(UUID_RE);
  return direct ? direct[0] : null;
}

function parseArtistFromTitle(title: string): string | null {
  // "Generated by KoBadger | Suno" -> "KoBadger"
  const m = title.match(/Generated by\s+([^|]+?)\s*\|/i);
  return m ? m[1].trim() : null;
}

/** Probe a remote audio URL's duration via ffmpeg (reads headers only). */
export function probeDuration(url: string): Promise<number | null> {
  return new Promise((resolve) => {
    const proc = spawn(config.ffmpegPath, ['-hide_banner', '-i', url], { windowsHide: true });
    let stderr = '';
    proc.stderr.on('data', (d) => {
      stderr += d.toString();
    });
    const timer = setTimeout(() => {
      try {
        proc.kill();
      } catch {
        /* ignore */
      }
    }, 15000);
    timer.unref?.();
    proc.on('exit', () => {
      clearTimeout(timer);
      const m = stderr.match(/Duration:\s*(\d+):(\d+):(\d+\.?\d*)/);
      if (!m) return resolve(null);
      resolve((Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3])) * 1000);
    });
    proc.on('error', () => {
      clearTimeout(timer);
      resolve(null);
    });
  });
}

/** Resolve a Suno share link (suno.com/s/<slug>, /song/<uuid>, /embed/<uuid>) into a playable track. */
export async function resolveSuno(input: string): Promise<ResolvedVideo> {
  const trimmed = input.trim();
  const uuidOnly = !/^https?:/i.test(trimmed) && UUID_RE.test(trimmed);
  const url = uuidOnly ? `https://suno.com/song/${trimmed}` : trimmed.startsWith('http') ? trimmed : `https://${trimmed}`;
  if (!/(^|[./])suno\.com\//.test(url) && !UUID_RE.test(url)) {
    throw new SunoError('That does not look like a Suno link.');
  }

  let html = '';
  try {
    const res = await fetch(url, {
      redirect: 'follow',
      headers: { 'user-agent': UA, accept: 'text/html' },
    });
    if (!res.ok) throw new Error(`page returned ${res.status}`);
    html = await res.text();
  } catch (err) {
    throw new SunoError(`Could not reach Suno: ${err instanceof Error ? err.message : String(err)}`);
  }

  const uuid = extractUuid(url, html);
  if (!uuid) throw new SunoError('Could not find the track id in that Suno page.');

  const streamUrl = `https://cdn1.suno.ai/${uuid}.mp3`;
  try {
    const head = await fetch(streamUrl, { method: 'HEAD', headers: { 'user-agent': UA } });
    if (!head.ok) throw new Error(`audio returned ${head.status}`);
  } catch (err) {
    throw new SunoError(`Could not reach the Suno audio: ${err instanceof Error ? err.message : String(err)}`);
  }

  const title = html.match(/<meta property="og:title" content="([^"]+)"/);
  const image = html.match(/<meta property="og:image" content="([^"]+)"/);
  const pageTitle = html.match(/<title>([^<]*)<\/title>/);
  const name = title ? title[1] : 'Suno track';
  const artist = parseArtistFromTitle(pageTitle?.[1] ?? '') ?? 'Suno';
  const durationMs = (await probeDuration(streamUrl)) ?? 0;

  return {
    videoId: uuid,
    uri: `suno:${uuid}`,
    name,
    artists: [artist],
    album: 'Suno',
    durationMs,
    image: image?.[1] || undefined,
    source: 'suno',
    streamUrl,
    channel: artist,
    thumbnail: image?.[1] || undefined,
  };
}
